### ISSUE TITLE
[BUG] Drones consume batteries instead of charging from power grid.

### ISSUE THREAD

**Issue by mikeloeven** [Darkplate911/DI_Transportation#2]
Reporting as a bug since the mod advertises itself as a replacement for X3  Transportation. Currently drones are Not a faithful port of the original as the drones are back to vanilla behavior of consuming batteries instead of charging from power grid defeating one of the main purposes of the orignal the mod. Primary reason I used X3 was because I was completely disgusted with the whole concept of drones consuming disposable batteries en mass as it was a dumb and contrived game mechanic that made little sense to me when you have a power grid with rechargeable energy storage. Please update the drones to work like they did in the original mod or at least provide at the very least a toggle able option for this. We need the Rechargeable electric vehicles back

**Comment by Darkplate911** [comment]
This mod only works on Blueprints in UE4. This will contain no C++ Code so this mod will be easily updated to the next update. C++ code is required for that to work so it is not possible. I did add a recipe to create batteries 200/min. and that should make life a lot easier for you.
