### ISSUE TITLE
DI Locomotives seem to ignore station wait times

### ISSUE THREAD

**Issue by mikeloeven** [Darkplate911/DI_Transportation#3]
Behavior observed on a bidirectional personal transport line. 
4 Stations    arranged like so 1<---2<3>---4>
End station 4 is a full size vanilla station the two middle and second end station are both small stations 
Locomotive configuration is just two DI 200's back to back for a fast transport line no cargo. 
Time table is as follows Station 1 > 3 > 4 > 2 >1 
wait setting load / unload AND wait 30 seconds 

Observed behavior locomotives immediately move to the next station as soon as the train comes to a complete stop ignoring wait time

**Comment by Darkplate911** [comment]
The train is build off the parent. Only changes was speed. I am unable to modify the parent because coffee stains would need to do that. I remodified the trains and have added faster trains it now can support.
