### ISSUE TITLE
DI Freight Car 512 incorrect fluid capacity

### ISSUE THREAD

**Issue by LimeSucker** [Darkplate911/DI_Transportation#4]
Hello !

The title pretty much says it all, I tried both 390 & 512 Freight cars but they only hold 1600 m^3 of fluid 
![image](https://user-images.githubusercontent.com/85787698/169078268-4f489c90-63f3-4fb5-86a8-589b4031ae3d.png)

Can the issue come from the fact that Oxygen is a modded fluid ? (From More Alternate Recipes)

**Comment by Darkplate911** [comment]
I will have to look into that. Btw why is it not gas?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: LimeSucker ***@***.***>
Sent: Wednesday, May 18, 2022 8:20:01 AM
To: Darkplate911/DI_Transportation ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Darkplate911/DI_Transportation] DI Freight Car 512 incorrect fluid capacity (Issue #4)


Hello !

The title pretty much says it all, I tried both 390 & 512 Freight cars but they only hold 1600 m^3 of fluid
[image]<https://user-images.githubusercontent.com/85787698/169078268-4f489c90-63f3-4fb5-86a8-589b4031ae3d.png>

Can the issue come from the fact that Oxygen is a modded fluid ? (From More Alternate Recipes)

**Comment by LimeSucker** [comment]
The weird thing is, when stored elsewhere than the freight car, it seems like it's considered as a gas 
![image](https://user-images.githubusercontent.com/85787698/169082228-8aebf224-9442-4c6d-bd91-688058eadc27.png)

**Comment by Darkplate911** [comment]
I am wondering if this is a train gas issue. That means the vanilla is bugged as well.  I will check it as soo. As I am off work at 5pm pst

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Darkplate911** [comment]
Apparently there was a change in the parent so I found it and will release the fix soon

***@***.***
***@***.***

**Comment by Darkplate911** [comment]
DI Transportation Version 0.1.1

  *   corrected the wagon fluid size showing incorrectly (found by LimeSucker)
* rebalenced train power usage since there are more trains out now that this became a cheat. Not no more.
* Mo balancing will be soon to other parts.

**Comment by Darkplate911** [comment]
The release 0.1.1 resolved the issue

**Comment by LimeSucker** [comment]
Thanks for the fix. However I think there's something that's making the game crash everytime I load my save with your mod installed (disabling / desinstalling the mod doesn't crash the game).

`Fatal error: [File:C:/ar-sml/_work/SatisfactoryModLoader/SatisfactoryModLoader/SML/Plugins/SML/Source/SML/Private/Registry/ModContentRegistry.cpp] [Line: 410] Attempt to register invalid content in mod content registry: Attempt to register NULL Schematic. Mod Reference: DI_Transportation_Darkplate. Script callstack: Unable to display Script Callstack. Compile with DO_BLUEPRINT_GUARD=1`

This is the relevant error I found

**Comment by Darkplate911** [comment]
Come into vchat in satisfactory modding is discord
